
/* dies ist eine komentar zeile
dir
pause
/* das file attribut „ndern
chmod cli.tos 1
dir cli.*
chmod cli.tos 0
dir cli.*
pause
/* einen ordner auf machen
md affe
dir affe
pause
/* einen leeren ordner l”schen
rd affe\
dir affe
pause
/* files umbenennen
ren cli.tos cli.prg
dir cli.*
pause
/* den disk status zeigen
show
pause
/* files kopieren und umbenennen
copy cli.prg cli.xxx
dir cli.*
pause
/* files l”schen
rm cli.xxx
dir cli.*
pause
/* hilfe
help
pause
/* zeit „ndern und anzeigen
time
time 01.02.03 31:02:99
/* die tos versions nummer ausgeben
version
/* farbe umschalten
invers
/* schont die augen
pause
invers
/* verify aus schalten
verify off
verify
/* verify an schalten
verify on
pause
/* noch platz im speicher ?
free_mem
pause
info
