GEMLIB: Specific UDEF functions
Specific UDEF functions
VDI Function Reference
This section contains all VDI functions that have a specific UDEF version.
Functions
void udef_vst_error (VdiHdl, short mode, short *errorvar)
short udef_v_loadcache (VdiHdl, const char *filename, short mode)
short udef_v_savecache (VdiHdl, const char *filename)
void udef_v_bit_image (VdiHdl, const char *filename, short aspect, short x_scale, short y_scale, short h_align, short v_align, short *pxy)
void udef_vm_filename (VdiHdl, const char *filename)
void udef_v_alpha_text (VdiHdl, const char *str)
void udef_v_curtext (VdiHdl, const char *str)
void udef_vqt_extent (VdiHdl, const char *str, short extent[])
void udef_vrq_string (VdiHdl, short len, short echo, short echoxy[], char *str)
short udef_vsm_string (VdiHdl, short len, short echo, short echoxy[], char *str)
void udef_v_gtext (VdiHdl, short x, short y, const char *str)
void udef_v_justified (VdiHdl, short x, short y, const char *str, short len, short word_space, short char_space)
void udef_v_bez (short handle, short count, short *xyarr, char *bezarr, short *extent, short *totpts, short *totmoves)
void udef_v_bez_fill (short handle, short count, short *xyarr, char *bezarr, short *extent, short *totpts, short *totmoves)
void udef_v_ftext (VdiHdl, short x, short y, const char *str)
void udef_v_ftext_offset (VdiHdl, short x, short y, const char *str, const short *offset)
void udef_v_ftext_offset16 (VdiHdl, short x, short y, const WCHAR *wstr, const short *offset)
void udef_v_ftext_offset16n (VdiHdl, short x, short y, const WCHAR *wstr, short num, const short *offset)
short udef_vq_devinfo (VdiHdl, short device, short *dev_exists, char *file_name, char *device_name)
void udef_vqt_f_extent (VdiHdl, const char *str, short extent[])
void udef_vqt_fontheader (VdiHdl, char *buffer, char *pathname)
short udef_vqt_name_and_id (VdiHdl, short font_format, char *font_name, char *ret_name)
void udef_vqt_real_extent (VdiHdl, short x, short y, char *string, short extent[])
short udef_vst_name (VdiHdl, short font_format, char *font_name, char *ret_name)
long udef_vq_hilite_color (short handle, COLOR_ENTRY *hilite_color)
short udef_vs_document_info (short vdi_handle, short type, char *s, short wchar)
Detailed Description
This section contains all VDI functions that have a specific UDEF version.
Other UDEF functions are just an alias (define) to the standard VDI function.
When FORCE_GEMLIB_UDEF is defined by gemlib user, these functions will be used in place of their standard VDI version. See UDEF version of VDI functions for details.
Warning
These functions are not multithread safe, and should be reserved for userdef usage, as suggested in UDEF version of VDI functions.
Function Documentation
void udef_v_alpha_text (short handle, const char * str)
UDEF version of v_alpha_text(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_v_bez (short handle, short count, short * xyarr, char * bezarr, short * extent, short * totpts, short * totmoves)
UDEF version of v_bez(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX.
void udef_v_bez_fill (short handle, short count, short * xyarr, char * bezarr, short * extent, short * totpts, short * totmoves)
UDEF version of v_bez_fill(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX.
void udef_v_bit_image (short handle, const char * filename, short aspect, short x_scale, short y_scale, short h_align, short v_align, short * pxy)
UDEF version of v_bit_image(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_v_curtext (short handle, const char * str)
UDEF version of v_curtext(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_v_ftext (short handle, short x, short y, const char * str)
UDEF version of v_ftext(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_v_ftext_offset (short handle, short x, short y, const char * str, const short * offset)
UDEF version of v_ftext_offset(). See UDEF version of VDI functions for details about UDEF feature
References VDI_PTSINMAX, and vdi_str2array_n().
void udef_v_ftext_offset16 (short handle, short x, short y, const WCHAR * wstr, const short * offset)
UDEF version of v_ftext_offset16(). See UDEF version of VDI functions for details about UDEF feature
References VDI_PTSINMAX, and vdi_wstrlen().
void udef_v_ftext_offset16n (short handle, short x, short y, const WCHAR * wstr, short num, const short * offset)
UDEF version of v_ftext_offset16n(). See UDEF version of VDI functions for details about UDEF feature
References VDI_PTSINMAX.
void udef_v_gtext (short handle, short x, short y, const char * str)
UDEF version of v_gtext(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_v_justified (short handle, short x, short y, const char * str, short len, short word_space, short char_space)
UDEF version of v_justified(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
short udef_v_loadcache (short handle, const char * filename, short mode)
UDEF version of v_loadcache(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
short udef_v_savecache (short handle, const char * filename)
UDEF version of v_savecache(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_vm_filename (short handle, const char * filename)
UDEF version of vm_filename(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
short udef_vq_devinfo (short handle, short device, short * dev_exists, char * file_name, char * device_name)
UDEF version of vq_devinfo(). See UDEF version of VDI functions for details about UDEF feature
long udef_vq_hilite_color (short handle, COLOR_ENTRY * hilite_color)
UDEF version of vq_hilite_color(). See UDEF version of VDI functions for details about UDEF feature
void udef_vqt_extent (short handle, const char * str, short extent[])
UDEF version of vqt_extent(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_vqt_f_extent (short handle, const char * str, short extent[])
UDEF version of vqt_f_extent(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_vqt_fontheader (short handle, char * buffer, char * pathname)
UDEF version of vqt_fontheader(). See UDEF version of VDI functions for details about UDEF feature
References vdi_array2str().
short udef_vqt_name_and_id (short handle, short font_format, char * font_name, char * ret_name)
UDEF version of vqt_name_and_id(). See UDEF version of VDI functions for details about UDEF feature
References vdi_array2str(), VDI_INTINMAX, and vdi_str2array_n().
void udef_vqt_real_extent (short handle, short x, short y, char * string, short extent[])
UDEF version of vqt_real_extent(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
void udef_vrq_string (short handle, short len, short echo, short echoxy[], char * str)
UDEF version of vrq_string(). See UDEF version of VDI functions for details about UDEF feature
References vdi_array2str().
short udef_vs_document_info (short handle, short type, char * s, short wchar)
UDEF version of vs_document_info(). See UDEF version of VDI functions for details about UDEF feature
References VDI_INTINMAX, and vdi_str2array_n().
short udef_vsm_string (short handle, short len, short echo, short echoxy[], char * str)
UDEF version of vsm_string(). See UDEF version of VDI functions for details about UDEF feature
References vdi_array2str().
void udef_vst_error (short handle, short mode, short * errorvar)
UDEF version of vst_error(). See UDEF version of VDI functions for details about UDEF feature
short udef_vst_name (short handle, short font_format, char * font_name, char * ret_name)
UDEF version of vst_name(). See UDEF version of VDI functions for details about UDEF feature
References vdi_array2str(), VDI_INTINMAX, and vdi_str2array_n().