GEMLIB: VDI output functions
VDI output functions
VDI Function Reference
output functions
Functions
void v_arc (VdiHdl, short x, short y, short radius, short begang, short endang)
void v_bar (VdiHdl, short pxy[])
void v_cellarray (VdiHdl, short pxy[], short row_length, short elements, short nrows, short write_mode, short colarray[])
void v_circle (VdiHdl, short x, short y, short radius)
void v_contourfill (VdiHdl, short x, short y, short color_idx)
void v_ellarc (VdiHdl, short x, short y, short xrad, short yrad, short begang, short endang)
void v_ellipse (VdiHdl, short x, short y, short xrad, short yrad)
void v_ellpie (VdiHdl, short x, short y, short xrad, short yrad, short begang, short endang)
void v_fillarea (VdiHdl, short count, short pxy[])
void v_gtext (VdiHdl, short x, short y, const char *str)
void v_gtext16 (VdiHdl, short x, short y, const short *wstr)
void v_gtext16n (VdiHdl, PXY pos, const short *wstr, short num)
void v_justified (VdiHdl, short x, short y, const char *str, short len, short word_space, short char_space)
void v_justified16n (VdiHdl, short x, short y, const short *wstr, short num, short len, short word_space, short char_space)
void v_pieslice (VdiHdl, short x, short y, short radius, short begang, short endang)
void v_pline (VdiHdl, short count, short pxy[])
void v_pmarker (VdiHdl, short count, short pxy[])
void v_rbox (VdiHdl, short pxy[])
void v_rfbox (VdiHdl, short pxy[])
void vr_recfl (VdiHdl, short pxy[])
Detailed Description
output functions
todo: add description here
Function Documentation
void v_arc (short handle, short x, short y, short radius, short begang, short endang)
draws an arc, whose start and end angle can be set in tenths of degrees from 0 to 3600.
Parameters
handle Device handle
x x-coordinate of center point of arc
y y-coordinate of center point of arc
radius radius
begang start angle (in tenths of degrees 0-3600)
endang end angle (in tenths of degrees 0-3600)
Since
all VDI versions
References VDI_CNTRLMAX.
void v_bar (short handle, short pxy[])
draws a filled rectangle. In contrast to "FILLED RECTANGLE" a border is drawn.
Parameters
handle Device handle
pxy coordinates of the rectangle
Since
all VDI versions
References VDI_CNTRLMAX.
void v_cellarray (short handle, short pxy[], short row_length, short elements, short nrows, short write_mode, short colarray[])
With the Cell Array function, the device draws a rectangular array defined by the input parameter (x,y) coordinates and the color index array. The lower left and upper right coordinates define the extent of the rectangle. GEM VDI divides the rectangle into cells based on the number of rows and columns specified as input parameters. The color index array specifies the color for each cell.
Parameters
handle Device handle
pxy
row_length Length of each row in color index array(size as declared in a high-level language).
elements Number of elements used in each row of color index array
nrows Number of rows in color index array.
write_mode Pixel operation to be performed
colarray Color index array, stored by row.
Since
all VDI versions
Each cell of the rectangle is mapped to pixels on the display surface. The pixel takes the color of the cell that covers its center.
If the device does not support cell arrays, the device outlines the area with a solid line in the current line color and line width.
Note: This function is not required and may not be available on all devices.
References VDI_CNTRLMAX.
void v_circle (short handle, short x, short y, short radius)
draws a filled circle
Parameters
handle Device handle
x x-coordinate of center point of circle
y y-coordinate of center point of circle
radius radius
Since
all VDI versions
References VDI_CNTRLMAX.
void v_contourfill (short handle, short x, short y, short index)
fills an area which is limited by another color or the edges of the display. Use this function on the screen only!
Parameters
handle Device handle
x
y
index color index
Since
all VDI versions
References VDI_CNTRLMAX.
void v_ellarc (short handle, short x, short y, short xrad, short yrad, short begang, short endang)
draw an elliptical arc, whose start and end angle can be set in tenths of degrees from 0 to 3600.
Parameters
handle Device handle
x x-coordinate of center point of arc
y y-coordinate of center point of arc
xrad Radius of X-axis
yrad Radius of Y-axis
begang start angle (in tenths of degrees 0-3600), counterclockwise.
endang end angle(in tenths of degrees 0-3600).
Since
all VDI versions
References VDI_CNTRLMAX.
void v_ellipse (short handle, short x, short y, short xrad, short yrad)
Parameters
handle Device handle
x
y
xrad
yrad
Since
all VDI versions
References VDI_CNTRLMAX.
void v_ellpie (short handle, short x, short y, short xrad, short yrad, short begang, short endang)
draws a filled elliptical arc, whose start and end angle can be selected in tenths of degrees from 0 to 3600.
Parameters
handle Device handle
x
y
xrad horizontal radius
yrad vertical radius
begang start angle
endang end angle
Since
all VDI versions
References VDI_CNTRLMAX.
void v_fillarea (short handle, short count, short pxy[])
draws a filled area, for example a complex polygon.
Parameters
handle Device handle
count
pxy coordinates
Since
all VDI versions
The area is filled using the following current attributes:
fill area color
interior style (hollow, solid, pattern, hatch or user-defined)
writing mode
style index
The area is outlined with a solid line of the current fill area color if the fill area perimeter visibility is on, which is the default at Open Workstation. *
References VDI_CNTRLMAX.
void v_gtext (short handle, short x, short y, const char * str)
draws a string with the selected text attributes.
Parameters
handle Device handle
x
y
str string
Since
all VDI versions
If you have selected a vector font, neither pair nor track kerning are used and the character widths are non-fractional (that means the widths returned by vqt_width()).
References VDI_CNTRLMAX, VDI_INTINMAX, and vdi_str2array_n().
void v_gtext16 (short handle, short x, short y, const short * wstr)
same as v_gtext()
Parameters
handle Device handle
x
y
wstr string, with 16 bits per character.
Since
all VDI versions
References VDI_CNTRLMAX, and vdi_wstrlen().
void v_gtext16n (short handle, PXY pos, const short * wstr, short num)
same as v_gtext()
Parameters
handle Device handle
pos
wstr string, with 16 bits per character.
num len of the string
Since
all VDI versions
References VDI_CNTRLMAX.
void v_justified (short handle, short x, short y, const char * str, short len, short word_space, short char_space)
outputs graphic text and lengthens or shortens the string by modifying the interword or intercharacter spacing
Parameters
handle Device handle
x
y
str string
len length in pixels
word_space <> 0: Wortzwischenr„ume dehnen
char_space <> 0: Zeichenzwischenr„ume dehnen
Since
all VDI versions
If you use a vector font, the requested width of the string refers to the sum of the character widths - characters extending beyond the left or right edge of the em square are ot taken into account.
References VDI_CNTRLMAX, VDI_INTINMAX, and vdi_str2array_n().
void v_justified16n (short handle, short x, short y, const short * wstr, short num, short len, short word_space, short char_space)
outputs graphic text and lengthens or shortens the string by modifying the interword or intercharacter spacing
Parameters
handle Device handle
x
y
wstr string
num string len
len length in pixels
word_space <> 0: Wortzwischenr„ume dehnen
char_space <> 0: Zeichenzwischenr„ume dehnen
Since
all VDI versions
If you use a vector font, the requested width of the string refers to the sum of the character widths - characters extending beyond the left or right edge of the em square are ot taken into account.
References VDI_CNTRLMAX, and VDI_INTINMAX.
void v_pieslice (short handle, short x, short y, short radius, short begang, short endang)
draws a filled arc, whose start and end angle can be set in tenths of degrees from 0 to 3600.
Parameters
handle Device handle
x
y
radius radius
begang start angle
endang end angle
Since
all VDI versions
References VDI_CNTRLMAX.
void v_pline (short handle, short count, short pxy[])
connects all points in pxy with lines
Parameters
handle Device handle
count
pxy coordinates
Since
all VDI versions
References VDI_CNTRLMAX.
void v_pmarker (short handle, short count, short pxy[])
draws markers
Parameters
handle Device handle
count
pxy coordinates
Since
all VDI versions
References VDI_CNTRLMAX.
void v_rbox (short handle, short pxy[])
draws an unfilled rectangle with rounded corners
Parameters
handle Device handle
pxy coordinates
Since
all VDI versions
References VDI_CNTRLMAX.
void v_rfbox (short handle, short pxy[])
A filled rectangle with rounded corners is drawn by this function.
Parameters
handle Device handle
pxy Koordinaten
Since
all VDI versions
References VDI_CNTRLMAX.
void vr_recfl (short handle, short pxy[])
draw a filled rectangle (without outline).
Parameters
handle Device handle
pxy coordinates
Since
all VDI versions
References VDI_CNTRLMAX.